# generated by zon2nix (https://github.com/nix-community/zon2nix)

{ linkFarm, fetchzip, fetchgit }:

linkFarm "zig-packages" [
  {
    name = "zeit-0.6.0-5I6bk36tAgATpSl9wjFmRPMqYN2Mn0JQHgIcRNcqDpJA";
    path = fetchgit {
      url = "https://github.com/rockorager/zeit?ref=v0.7.0";
      rev = "7ac64d72dbfb1a4ad549102e7d4e232a687d32d8";
      hash = "sha256-CDYwSqx0xA3Xx7/eDCtP0lHbheIScPwnffV2nxzJ/mU=";
    };
  }
]
